imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    app.common.email: 'bob@archlinux.de'
    app.packages.mirror: 'http://mirror.leaseweb.net/archlinux/'
    app.packages.cgit: 'https://projects.archlinux.de/svntogit/'
    app.packages.repositories:
        core: ['x86_64', 'i686']
        extra: ['x86_64', 'i686']
        testing: ['x86_64', 'i686']
        community: ['x86_64', 'i686']
        community-testing: ['x86_64', 'i686']
        multilib: ['x86_64']
        multilib-testing: ['x86_64']
    app.packages.default_architecture: 'x86_64'
    app.mirrors.status: 'https://www.archlinux.org/mirrors/status/json/'
    app.mirrors.default: '%app.packages.mirror%'
    app.mirrors.country: 'DE'
    app.news.feed: 'https://bbs.archlinux.de/extern.php?action=feed&fid=257&type=atom&order=posted&show=15'
    app.news.archive: 'https://bbs.archlinux.de/viewforum.php?id=257'
    app.releng.releases: 'https://www.archlinux.org/releng/releases/json/'

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        news_feed_url: '%app.news.feed%'
    date:
        format: 'd.m.Y H:i'
    number_format:
        decimal_point: ','
        thousands_separator: '.'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
