app_start:
    path: /
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_impressum:
    path: /impressum
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_privacy:
    path: /privacy-policy
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_download:
    path: /download
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_packages:
    path: /packages
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_package:
    path: /packages/{repository}/{architecture}/{name}
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_news:
    path: /news
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_news_item:
    path: /news/{id<[0-9]+>}-{slug<[\w\-\.]+>}
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_mirrors:
    path: /mirrors
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_releases:
    path: /releases
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

app_release:
    path: /releases/{version}
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html.twig'
        sharedAge: 3600
        maxAge: 300

external_forum:
    path: /
    host: bbs.archlinux.de
    schemes: ['https']

external_wiki:
    path: /
    host: wiki.archlinux.de
    schemes: ['https']

external_aur:
    path: /
    host: aur.archlinux.de
    schemes: ['https']

external_contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: 'https://bbs.archlinux.de/misc.php?email=486'
