services:
    App\Command\Dev\:
        resource: '../src/Command/Dev/*'
        autowire: true
        autoconfigure: true

    cache.adapter.array:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
